// Demo data for guest mode users — a gaming showroom
export const guestActivities: any[] = [
  {
    id: "demo-game-1",
    userId: "guest",
    type: "game",
    title: "Elden Ring",
    category: "RPG",
    subcategory: "Action RPG",
    status: "in_progress",
    progress: 65,
    rating: 5,
    totalHours: 87,
    tier: "S",
    imageUrl: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg",
    description: "An epic dark fantasy adventure",
    tags: ["souls-like", "open-world", "challenging"],
    metadata: {},
    externalId: null,
    isPublic: 1,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: "demo-game-2",
    userId: "guest",
    type: "game",
    title: "Baldur's Gate 3",
    category: "RPG",
    subcategory: "Turn-Based",
    status: "completed",
    progress: 100,
    rating: 5,
    totalHours: 156,
    tier: "S",
    imageUrl: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1086940/header.jpg",
    description: "The best D&D adventure in gaming",
    tags: ["d&d", "story-rich", "multiplayer"],
    metadata: {},
    externalId: null,
    isPublic: 1,
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: "demo-game-3",
    userId: "guest",
    type: "game",
    title: "Hollow Knight",
    category: "Metroidvania",
    subcategory: "Platformer",
    status: "wishlist",
    progress: 0,
    rating: null,
    totalHours: 0,
    tier: null,
    imageUrl: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/367520/header.jpg",
    description: "Beautiful hand-drawn metroidvania",
    tags: ["metroidvania", "indie", "challenging"],
    metadata: { priority: "high", estimatedHours: 40 },
    externalId: null,
    isPublic: 1,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: "demo-game-4",
    userId: "guest",
    type: "game",
    title: "Hades II",
    category: "Roguelike",
    subcategory: "Action",
    status: "in_progress",
    progress: 40,
    rating: 4,
    totalHours: 32,
    tier: "A",
    imageUrl: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1145350/header.jpg",
    description: "Escape the Underworld — again",
    tags: ["roguelike", "indie", "mythology"],
    metadata: {},
    externalId: null,
    isPublic: 1,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: "demo-game-5",
    userId: "guest",
    type: "game",
    title: "Stardew Valley",
    category: "Simulation",
    subcategory: "Farming",
    status: "completed",
    progress: 100,
    rating: 5,
    totalHours: 210,
    tier: "S",
    imageUrl: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/413150/header.jpg",
    description: "The coziest farm in gaming",
    tags: ["cozy", "indie", "farming"],
    metadata: {},
    externalId: null,
    isPublic: 1,
    createdAt: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
];

export const guestSessions: any[] = [
  {
    id: "demo-session-1",
    activityId: "demo-game-1",
    userId: "guest",
    date: new Date().toISOString().split('T')[0], // Today
    duration: 2.5,
    notes: "Finally beat Malenia!",
    quality: 5,
    location: null,
  },
  {
    id: "demo-session-2",
    activityId: "demo-game-4",
    userId: "guest",
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // Yesterday
    duration: 1.5,
    notes: "New personal best run",
    quality: 4,
    location: null,
  },
  {
    id: "demo-session-3",
    activityId: "demo-game-1",
    userId: "guest",
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 2 days ago
    duration: 4.0,
    notes: "Exploring the Mountaintops of the Giants",
    quality: 5,
    location: null,
  },
  {
    id: "demo-session-4",
    activityId: "demo-game-2",
    userId: "guest",
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 5 days ago
    duration: 8.0,
    notes: "Final boss battle and ending — what an amazing journey!",
    quality: 5,
    location: null,
  },
];

export const guestStats = {
  totalActivities: 5,
  completedActivities: 2,
  inProgressActivities: 2,
  totalHours: 485,
  monthlyHours: 42.5,
  totalGames: 5,
  completedGames: 2,
  byType: {
    game: { count: 5, completed: 2, hours: 485 },
  },
};
